### ISSUE TITLE
Malformed rendering of SVG "screenshot"

### ISSUE THREAD

**Issue by AllanLRH** [Luttik/pytest-locker#6]
Cool library, but it's a shame that the SVG "screenshot" in the README is rendered malformed, at least in Firefox on Mac:

You could consider using a PNG instead :)

The "screenshot" renders fine when I'm just viewing that (by clicking on it).

By the way, how did you make it?

<img width="1088" alt="Shot on Firefox@MacOS" src="https://user-images.githubusercontent.com/2641327/95648999-a0fd4300-0adb-11eb-9e6b-a569e25994cd.png">

**Comment by Luttik** [comment]
@AllanLRH Good catch. I used [carbon](https://carbon.now.sh/) to generate the image, it's a pretty neat tool IMHO.

**Comment by Luttik** [comment]
I think I'll leave it be since GitHub seems to block you from changing the image size if you use a png. And a super large image on the top of the page is undesirable in my opinion. I have embedded an image below so if you know a better way feel free to notify me or create a pull-request.

![Test image](https://user-images.githubusercontent.com/6634187/96420928-69d31400-11f6-11eb-93e2-b894f334ce8f.png)
